name: weather_probability_app
description: A beautiful Flutter app for weather probability analysis

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  http: ^0.13.5
  geolocator: ^11.0.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true